#!/bin/bash -e
#
# Source code post-build script complementary to the application server post-build script provided by STARTX.
# This script will be executed after the building process (s2i)
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

# app could be found in $APP_PATH
echo "OKD-DEMO-HUGO start post-build hook"
doApachePostBuild