#!/bin/bash -e
#
# Source code pre-deploy script complementary to the application server pre-deploy script provided by STARTX.
# This script will be executed before the deployement of a new container (or pod)
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

# app could be found in $APP_PATH
echo "OKD-DEMO-HUGO start pre-deployment hook"
doApachePreDeploy